### ISSUE TITLE
AttributeError: 'PluginManager' object has no attribute 'disable_plugins'

### ISSUE THREAD

**Issue by fredericmohr** [sh4nks/flask-plugins#11]
Hi, 

I always run into this error with your plugin example. It doesn't matter if I use virtualenv or plain python. flask-plugins is version 1.5 via pip.

    Traceback (most recent call last):
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/.venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/.venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/.venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/.venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/.venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/.venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/.venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/.venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/demian/GIT/python-apps/flask-plugin-example/example/app.py", line 39, in disable2
        plugin_manager.disable_plugins([plugin])
    AttributeError: 'PluginManager' object has no attribute 'disable_plugins'

I couldn't find anything about it in the docs. Has this feature been removed? Same with enable_plugins()

**Comment by fredericmohr** [comment]
It seems to me, that it's not really supported by flask to dynamically adjust routes at runtime so as far as I see it there is no way around restarting/reloading the server.

If someone has the same problem as me, maybe this'll help.

The way I solved the restart problem, was to run the flask app with another wsgi server that supports daemon mode (in my case gunicorn) and restart that by sending a HUP signal to the process. This doesn't work with the integrated server, since it's not running as a daemon and thus can't restart itself after it shut itself down. (Resulting in your app server just stopping)

    $ gunicorn --daemon app:app

and then have a route to restart the server

    @app.route('/restart-server/')
    def restart-server():
      os.kill(os.getpid(), signal.SIGHUP)

Which I then call via AJAX, so that I don't run into "could not load page" errors due to the server temporarily not being available.

    $ vi static/js/function.js
    function reload-server() {
      // Reload Server
      $.ajax({
        url: "/reload-server/"
      });
      // Wait 1 second and reload page
      setTimeout(function(){
        window.location = document.URL;
      }, 1000);
    }

And I call that with a simple button.

    <head><script src="/static/js/functions.js"></script></head>
    # wherever you want to put the button...
    <button onclick='reload-reload()'>Reload Server</button>

**Comment by wecosystem** [comment]
I've just started using this plugin and I agree the support for disabling is necessary. So, here's my implementation:

A new class:

    class PluginBlueprint(Blueprint):
        def render_or_redirect(self, template, **kwargs):
             from flask import render_template, url_for, redirect

            if os.path.isfile(self.root_path + '/plugin.disabled'):
                return redirect(url_for(self.name + '.disabled'))

            return render_template(template, **kwargs)

then in the plugin __init__.py I implement the blueprint like this:

    hello = PluginBlueprint("hello", __name__, template_folder="templates")

    @hello.route("/")
    def index():
        return hello.render_or_redirect(template="hello.html")

    @hello.route("/disabled")
    def disabled():
        return "Plugin disabled"

Now, just override the flask-plugins class for disable and enable to either delete a file called "plugin.disabled" or create it - depending on what action is called.

You could even take this a step further and add meta-data into the disable file to conditionally disable (e.g. disabled_until, or disabled_for: ['user1','user2'] etc.

This is just my 5 minute bus implementation - I will make this a little more generic, and secure over the course of the next couple of weeks.

But this is a good 'real-time' approach that doesn't require a server restart. It has a small I/O cost (checking file existence) but significantly less than if it were managed in a DB and the overhead of that.

I'd love to hear what you think about this solution and improvement ideas etc.

**Comment by fredericmohr** [comment]
I haven't worked in my flask project recently, so I'm a bit rusty when it comes to that, but if it works (and if you improve it over the coming weeks) it would be awesome if this would find its way into the flask-plugins code, so that it becomes easier to use it :+1:

**Comment by wecosystem** [comment]
Will probably be a little longer than expected. I've done some significant work on this to support on the fly enabling/disabling. This work includes support for checking the connect events and making sure only callbacks for "enabled" plugins are rendered out.

I've also changed the way events are connected (now done in the instance of the Plugin class) rather than standalone functions in the __init__.py (although for backwards compatibility this will still work). In the setup(), the developer can either call the connect_event() functions manually, or write the configure to info.json like:

    "connect_events": [
        {
            "connect_event": "after_navigation",
            "method": "some_method"
        }, 
    ]

I've tried to keep as much backwards compatibility as possible - but for what I need this thing to do, it's very likely I will be introducing breaking changes. Although, the framework this will become could be very useful for a lot of projects.

I'll pull request my changes when they are ready and you can decide if you want to build them into your plugin.

**Comment by sh4nks** [comment]
Nice, I am really looking forward to this. But how do you register/unregister routes without restarting the app?

**Comment by wecosystem** [comment]
There is no way to do this as all of that is compiled when the flask app fires up. 

However, I simply created a new method inheriting the Blueprint class called __render_or_redirect__ - this function renders the template in the absence of a plugin.disabled file in the plugin root; or renders the template as defined in the plugin route.

This means if someone uses this extension, and doesn't "render_or_redirect" their templates, then the content will show (and disabling, enabling won't matter). 

It's the best solution I could come up with that allows this plugin to be really useful in a high availability application.

I've also re-instated "enable" and "disable" methods into the Plugin class - these do as they are named. The methods control the creation and removal of the plugin.disabled folder as well as updating the status of the Plugin's self.enabled property.

**Comment by sh4nks** [comment]
See https://github.com/sh4nks/flask-plugins/commit/dacff3a3be74c96b611004fa72172b4d6875ae8a and https://github.com/sh4nks/flask-plugins/commit/9d0d2f55c74312335c509fb03fdefd1db8b92739.
