### ISSUE TITLE
Current maintainer active?

### ISSUE THREAD

**Issue by gnubyte** [sh4nks/flask-plugins#22]
Hello, 

Just checking to see if this plugin is still actively maintained - thank you!
If not can we use this issue as a means to discuss plans for maintaining going forward? 

Thank you!

**Comment by sh4nks** [comment]
Yes, I am still active. I just don't have enough time to tackle every issue as soon as it pops up. Also, I am not getting paid for any of this. There are zero open PR atm. Everybody is invited to contribute to this project by opening new PRs!

**Comment by gnubyte** [comment]
I'm interested.

> I am not using this extension anymore.

Just curious, did you switch to using something else instead?

Any idea what continuation/transfer of responsibility or ownership would look like?
Off the top of my head, primarily I think I would need access to:

- pypi package
- readthedocs
- developer/owner status on the repo itself

**Comment by sh4nks** [comment]
I am using pluggy ([here](https://github.com/flaskbb/flaskbb/tree/master/flaskbb/plugins)) now. Its a bit more complex to set up but its also more powerful.

Cool. First, I'd give you full write access to the repo and see how it goes, if thats ok for you.

**Comment by gnubyte** [comment]
Hey sh4nks that sounds good. Thank you!

I'll be using this as a cornerstone of a product I'm building so I'm happy to maintain this. Cheers.

**Comment by gnubyte** [comment]
For the time being I will be maintaining this repo to the best of my ability, with a watchful eye of sh4nks.

**Comment by sh4nks** [comment]
I have given you write access to this repo.
